### ISSUE TITLE
Error in uploading utterances on for my app 

### ISSUE THREAD

**Issue by Sanjeev2487** [Microsoft/LUIS-Samples#105]
Hi,
I am getting following errror while uploading utterance to my luis app. I tried following parameters but I always get the below response and some utterances do not get uploaded on my app.
batchSize = 25 (max Value = 100)
delayMS = 10000 (default = 500)
maxRetry = 10 (default = 5)

`{"response":
                  {"error":
                             {"code":"BadArgument","message":"A batch add operation is already in progress.Please wait until it's completed before sending another request."
                              }
                     }
}`

**Comment by v-geberr** [comment]
@Sanjeev2487  Hi Sanjeev, are you using one of the samples, if yes, which one. If now, please include the bit of code that is uploading to the batch. Are you sure the previous request returned before making the next request?

**Comment by Sanjeev2487** [comment]
Hi @v-geberr ,
Yes I am using code given at `LUIS-Samples/examples/build-app-programmatically-csv/` .
I have the json file of utterances and I have only modified `index.js` and `_upload.js` from that folder.
Basically I have tried various combination of batchSize, delayMS, maxRetry but have not able to upload utterances completely.
The funny thing is it uploads some utterances at each time I run the script and after many times running the script it uploads most of the utterances but still some utterance remains.  How to check if previous request was completed or not ?

**Comment by Sanjeev2487** [comment]
I have total of 375 utterances. I can not share the data as it's private.

**Comment by v-geberr** [comment]
The example saves the converted utterances into a file. The response of the [upload batch API](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c09) returns error or success for each item.  It is in the API doc page.

**Comment by Sanjeev2487** [comment]
Finally, I found a work around something like this.
Change the `batchSize` a couple of times and keep uploading the data until complete upload happens. While this might not be the ideal way it solves the issue.
