### ISSUE TITLE
build-app-programmatically-csv typo - Shouldn't entityList equal entities?

### ISSUE THREAD

**Issue by kbuchanan** [Microsoft/LUIS-Samples#106]
https://github.com/Microsoft/LUIS-Samples/blob/18be81e49e2538cdd6290c98b63d2bcde04aed49/examples/build-app-programmatically-csv/index.js#L53-L60

Noticed this while browsing the code.

**Comment by v-geberr** [comment]
Good catch. It should either equal entities or have a different name. I'll have to review the code that uses that property.
