### ISSUE TITLE
I don't understand how to add additional intents to this sample

### ISSUE THREAD

**Issue by bgarr33434** [Microsoft/LUIS-Samples#107]
Am I supposed to handle all intents through the Intent[Greetings] heading?  I've been inserting new sections for each new intent, as follows:
[LuisIntent("addresses")]
        public async Task AddressesIntent(IDialogContext context, LuisResult result)
        {
            await this.ShowLuisResult(context, result);
        }
        [LuisIntent("PhoneNumber")]
        public async Task PhoneNumberIntent(IDialogContext context, LuisResult result)
        {
            await this.ShowLuisResult(context, result);
        }
        [LuisIntent("Birthdays")]
        public async Task BirthdaysIntent(IDialogContext context, LuisResult result)
        {
            await this.ShowLuisResult(context, result);
        }  
Of course, none of these intents are ever hit.  When I use the Luis endpoint URI, the published URI is working just find and finds the correct intent and entities.  How do I get this to work on the BasicLuisDialog?

**Comment by v-geberr** [comment]
Which sample are you using? Did you start with this [tutorial](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-csharp-tutorial-build-bot-framework-sample)?

**Comment by bgarr33434** [comment]
Yes, and I switched out HomeAutomation for FamilyInfo.  One change that I just made, but it didn't matter, is I changed all references for [LuisIntent("Intentname")] to [LuisIntent("GarrFamilyInfo.Intentname")]

**Comment by v-geberr** [comment]
To figure out if the problem is the bot code or the connection to LUIS -- is your bot test utterance in the LUIS query log? If no, make sure the LUIS app id and the LUIS endpoint key are correct in the bot settings in the Azure portal. If yes, than focus on the intent code. Have you looked at the bot logs?

**Comment by bgarr33434** [comment]
Thanks...so it appears that after I created GarrFamilyInfo, the system created GarrFamilyBot-a0ee, and all of the requests are going to that.  I don't understand why because I am using the published info from GarrFamilyInfo in the  Dialog.cs file

**Comment by v-geberr** [comment]
Is GarrFamilyInfo the LUIS app name? The bot isn't [connected to LUIS](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-csharp-tutorial-build-bot-framework-sample#connect-your-luis-app-to-the-bot) by app name but by app id.

**Comment by bgarr33434** [comment]
PS, working fine, thanks for the hints
