### ISSUE TITLE
Incomplete response for `Get Intent` APIs

### ISSUE THREAD

**Issue by igauravsehrawat** [Microsoft/LUIS-Samples#108]
Apologies, if this is not the right place for this issue.

Issue:
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c1a

This API doesn't have utterances related to particular intent, which defeats the purpose. It would be extremely helpful to have utterances included.

Thanks

**Comment by igauravsehrawat** [comment]
Apologies for late reply.
The primary reason of the issue is to get the utterance related to that particular intent in intent API.
1. The intent API doesn't give you that. 
2. Now to get utterance for particular intent you need to get all utterances and then  filter it by that intent, which seems to be inefficient.

Just wanted to clarify that, I may be wrong.

Thanks

**Comment by diberry** [comment]
@igauravsehrawat I believe you have the correct method, inefficient but available. I'm closing this, feel free to reopen with more information.
