### ISSUE TITLE
PYTHON CLI - Add different ways of using command line arguments

### ISSUE THREAD

**Issue by Guilhermeslucas** [Microsoft/LUIS-Samples#109]
Hi all, really nice repository, helped me a lot while learning LUIS. I was walking throught [this codes](https://github.com/Microsoft/LUIS-Samples/blob/master/documentation-samples/authoring-api-samples/python/add-utterances-3-6.py) and wondering if it would be nice to have some another way of using this code as a command line application, using [argparse](https://docs.python.org/3/howto/argparse.html) or [click](http://click.pocoo.org/5/) .
This way, we could have operantions like : 

```
pyhton3 add-uterances.py --add-entity orderPizza
```

Keep the good work, guys!

**Comment by v-geberr** [comment]
@Guilhermeslucas Sorry this has taken so long to get back to. A python cli is a good idea to add to the samples.

**Comment by diberry** [comment]
@Guilhermeslucas Closing this now. Feel free to reopen or create a Python-based PR.
