### ISSUE TITLE
[Suggestion] Identify entities for Hybrid (English/Chinese) text

### ISSUE THREAD

**Issue by alucard001** [Microsoft/LUIS-Samples#110]
I am currently working with MS LUIS.ai and my receiving string (or utterance) contains both English and Chinese.

While English is just fine for LUIS because a sentence has space that can be split into words.  However, in Chinese (Both Traditional and Simplified) or English/Chinese in a single sentence,  there is no "space" between different words.

So if a person ask a question, under LUIS platform we cannot discover the "entities" within.

Are there any ways/methods/tricks that can be used so that when someone enter the whole string directly will LUIS.ai be able to identify it into different intent?

Thank you very much in advance for all your help.

**Comment by v-geberr** [comment]
Mixed language entities are not supported but you can play with adding mixed values to a phrase list.
