### ISSUE TITLE
Anything for Hindi support ?

### ISSUE THREAD

**Issue by anirugu** [Microsoft/LUIS-Samples#114]
I am looking for Hindi support in Luis. Hindi words can contain half other word to produce single character. for example

तू  = त + U = (You) When someone type this kind of sentence in Luis. Luis failed to handle the hindi characters.

Any solution for problem like this. FYI Wit.ai support Hindi.

**Comment by anirugu** [comment]
I tried with En-us. 

Thanks for reply. I have one more things to share. In Asian Country Like India people like to Talk & chat Hinglish.  It's combination of both.

If one culture can support both (Hindi and English) it will be wonderful. Currently Swift Key in Android have a language called Hinglish.

**Comment by v-geberr** [comment]
Thank you @anirugu. I'll close this now.

**Comment by anirugu** [comment]
Just let you know last week I tried to use Hindi in Japanese region and it's making some result.
