### ISSUE TITLE
Deprecated Entities

### ISSUE THREAD

**Issue by t-jemora** [Microsoft/LUIS-Samples#154]
When importing the json file, this error appears:
"The following prebuilt entities are deprecated: For geography: Please stay tuned for a future alternative."

**Comment by v-geberr** [comment]
@t-jemora Hi Jenny, Thanks for reporting this. Geography is now deprecated fully. Which file were you importing?

**Comment by t-jemora** [comment]
Thanks for the quick fix! LuisBot.json

**Comment by t-jemora** [comment]
Hi @v-geberr unfortunately the same error is still appearing.

**Comment by v-geberr** [comment]
@t-jemora Hi Jenny, did this get resolved? Is there anything more that needs to be done?

**Comment by cmanoliu** [comment]
Hello, 

I'm getting the same error when trying to import "LuisBot.json" from \bot-integration-samples\hotel-finder\csharp. 
Can you provide a working model for this sample, please ?
Thank you.

Regards,

PS it's annoying when things are intentionnaly broken (deprecated) without providing a working alternative. 'Please stay tuned for a future alternative.' is not acceptable...

**Comment by v-geberr** [comment]
@cmanoliu Thank you for reporting that the hotel sample JSON still needed to be fixed. The geography entity is removed, and the bot should work. I verified the C# code works with the edited LuisBot.json file. 

I appreciate that you took the time to log the bug. 

LUIS wants to provide an easy and successful NLP solution. Occasionally that means removing features until they operate at the standard LUIS expects.

**Comment by cmanoliu** [comment]
Thank you @v-geberr, I managed to upload (import) the model now.

What I meant in my remark is that breaking changes should be documented. At least, when you introduce one, the related error message should provide some hints for an alternative solution. Just saying to “stay tuned” is not one. This may cost money to your clients as it may prevent existing code from functioning.

**Comment by v-geberr** [comment]
Fixed. Please reopen if you need to.
