### ISSUE TITLE
Greetings / Thanks / insults Prebuilt Domains 

### ISSUE THREAD

**Issue by FKSI** [Microsoft/LUIS-Samples#188]
Hi there,

I'd like to know is there any prebuilt domains (or export) of greetings/thanks/insults intents?

thx

**Comment by FKSI** [comment]
Hey @diberry!

It make senses but right now LUIS is lacking behind because of such easy feature :(. 
What it's the recommend feature?
When the Personality Chat (I saw it at Build) will be available for NodeJS?

**Comment by diberry** [comment]
@FKSI I don't have know when Personality Chat will move to Nodejs.
