### ISSUE TITLE
LUIS response 406 

### ISSUE THREAD

**Issue by ruisilva450** [Microsoft/LUIS-Samples#214]
Hi,
Every now and then my subscription key seems to expire and starts to return 406 as response.
The only "fix" so far is to regenerate a new sub key

**Comment by diberry** [comment]
@ruisilva450 Thank you for posting this issue. In order to provide proper answers, please sign in to the LUIS portal and submit this issue via Support -> General Inquiry through User Voice. Please include, your app Id, authoring key, and endpoint query key.
