### ISSUE TITLE
Luis app is not returning intents property in json 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/LUIS-Samples#227]
I have noticed this change luis app since 2 days where I see json returned after querying luis app does not have intents property anymore . Here is the screenshot of what I see when I query my model.

![image](https://user-images.githubusercontent.com/32375467/46100128-4a3f9d80-c18e-11e8-865b-8b4bf4e76a49.png)

Has anything changed recently ? as I see some UI updates on luis UI as well?

**Comment by diberry** [comment]
@rjgmail88 You need to make sure to set the verbose querystring property to true. I'm closing this issue, feel free to reopen if the problem continues after you set verbose=true.
