### ISSUE TITLE
azure-function-endpoint

### ISSUE THREAD

**Issue by wiazur** [Microsoft/LUIS-Samples#243]
The `run.csx` file has outdated code that does not comply with the method signatures of a function app in the Azure portal. The Azure portal's in-portal function app uses this as its base:
```
#r "Newtonsoft.Json"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");

    string name = req.Query["name"];

    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    return name != null
        ? (ActionResult)new OkObjectResult($"Hello, {name}")
        : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
}
```
Whereas the `run.csx` file of the `azure-function-endpoint` sample uses a different task method signature: `public static async Task<HttpResponseMessage> Run(HttpRequest req, ILogger log)`.

Therefore, copying and pasting the `run.csx` file into Azure, over the above code, doesn't work.

**Comment by diberry** [comment]
@wiazur Hi Winona, did you ever get this resolved?

**Comment by wiazur** [comment]
@diberry thanks, I haven't. But working on other things, so it's not a hot issue.

**Comment by diberry** [comment]
Closing for now
