### ISSUE TITLE
Response code 401 (Unauthorized) 

### ISSUE THREAD

**Issue by jamypad2918** [Microsoft/LUIS-Samples#248]
I'm getting a 401 error while debugging these samples, from this, I get to some inquires like.
Can I use LUIS without azure subscription locally? and publishing?
Can I use LUIS on bots without using either MS Bot framework or azure?
Is it possible using MS Bot framework without an azure subscription?

**Comment by diberry** [comment]
Hi @jamypad2918, Let me answer the questions one at a time:

401 usually indicates that you are using the endpoint key when you should use the authoring key, or the other way around. There is usually additional information in the HTTP error message returned from the API. 

Currently, LUIS has a free tier but must use Azure service. I'm not sure what you are asking about publishing but the app, currently, must be published in the Azure service.

You can use LUIS with other bot frameworks but it still must be connected to Azure.

You can use the Bot Framework, which is just an SDK, without the Azure subscription. That would be the web chat control most likely as other channels require some connection to Azure.

**Comment by diberry** [comment]
@jamypad2918 I'm closing this issue now. Feel free to reopen if you have more questions.

**Comment by jamypad2918** [comment]
thank you Diana. 👍 
I created a new luis model on my own account and updated the endpoint and it worked, I guess the luis keys on the samples are not available anymore :)

Greetings!
