### ISSUE TITLE
do we have api for adding multiple intents/utterences in a single call? It would be a great help if we have any 

### ISSUE THREAD

**Issue by amitkotecha** [microsoft/LUIS-Samples#258]
do we have api for adding multiple intents/utterences in a single call? It would be a great help if we have any

**Comment by dfberry** [comment]
@cahann @aliciaep Is this already on backlog?

**Comment by cahann** [comment]
No it's not on the backlog. We are trying to get users to focus on building on model at a time verses multiple.

**Comment by diberry** [comment]
@amitkotecha Can you look at [batch](https://westeurope.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9c09) to see if it partially what you are looking for?
