### ISSUE TITLE
Luis Features are created, but not visible 

### ISSUE THREAD

**Issue by francis-2mundos** [microsoft/LUIS-Samples#263]
I am currently working on a Luis application, which has up to 100 Features (aka Phrase Lists) and 145 intents. I got to a point where I'm being able to create new interchangeable, not-global Features normally, but they do not display in the application. Whenever I try to create another one with the same name, I have the error message saying that there's another Phrase List with the same name. I'm very far from reaching Luis limits regarding number of intents and phrase lists.
I'm currently on a S0 - Standard Tier, and I'd love some help on this.

**Comment by diberry** [comment]
Please post this issue in the current repo - https://github.com/Azure-Samples/cognitive-services-language-understanding.  Closing because this repo is archived.
