### ISSUE TITLE
LuisResult only returns one intent

### ISSUE THREAD

**Issue by yfan183** [Microsoft/LUIS-Samples#32]
In the endpoint JSON, it returns a list of intents, however in the code if I query LuisResult result and do result.Intents, it only returns one intent

**Comment by v-geberr** [comment]
Can you share which code sample/example you used and if the verbose flag was set? https://westus.dev.cognitive.microsoft.com/docs/services/5819c76f40a6350ce09de1ac/operations/5819c77140a63516d81aee78

**Comment by v-geberr** [comment]
Closing due to lack of information
