### ISSUE TITLE
LUIS-Samples app build-app-programmatically-csv syntax issue. - from BB

### ISSUE THREAD

**Issue by v-geberr** [Microsoft/LUIS-Samples#71]
@rjgmail88 Hi, regarding the [bug](https://github.com/Microsoft/BotBuilder/issues/4168#) on LUIS-Samples from the BotBuilder repo.

What operating system and version of node are you using? I can't see the error text. Please repost it so it shows in this issue.

**Comment by rjgmail88** [comment]
I using Mac X and Node version is v6.11.0

**Error:**

Exception has occurred: Error
SyntaxError: Unexpected token (
/{//path//}/_parse.js:71
const convert = async (config) => {
                      ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

This error comes when I forked the project https://github.com/Microsoft/LUIS-Samples/tree/master/examples/build-app-programmatically-csv
and just ran it with node.

Looks like its for every file which is imported in index.js. here is the snippet from index.js

const parse = require('./_parse');
const createApp = require('./_create');
const addEntities = require('./_entities');
const addIntents = require('./_intents');
const upload = require('./_upload');

if I comment 1st line then same syntax error will be on next file which is _create.js

**Comment by v-geberr** [comment]
I suspect it has to do with how the file end of lines are treated. I need to check -- give me a day.

**Comment by rjgmail88** [comment]
Sure. Thanks.

**Comment by stevengum97** [comment]
Sorry to interject, but to run the code you'll need a Node version of at least 7 or greater as the code uses async/await. 

E.g. in [`_entities.js`][entities] it indicates the version of Node used when writing the code.
```js
// node 7.x
// uses async/await - promises
```

  [entities]: https://github.com/Microsoft/LUIS-Samples/blob/master/examples/build-app-programmatically-csv/_entities.js

**Comment by rjgmail88** [comment]
Good catch Steven. It worked.

**Comment by stevengum97** [comment]
Awesome! 😄
